package burp.scripts.capabilities;

public enum ScriptCapability {
    VARIABLE_MUTATION,
    REQUEST_URL_MUTATION,
    REQUEST_METHOD_MUTATION,
    REQUEST_HEADER_MUTATION,
    REQUEST_BODY_MUTATION,
    REQUEST_AUTH_MUTATION,
    REQUEST_QUERY_MUTATION,
    FLOW_CONTROL,
    DEPENDENT_REQUEST,
    AD_HOC_NETWORK,
    SENSITIVE_DATA_ACCESS,
    HOST_INTEROP,
    UNSUPPORTED_API
}
