package burp.runner;

public enum FlowTargetResolutionForm {
    REQUEST_ID,
    COLLECTION_AND_REQUEST_ID,
    QUALIFIED_PATH,
    COLLECTION_FOLDER_AND_NAME,
    UNIQUE_NAME,
    CASE_INSENSITIVE_REQUEST_ID,
    CASE_INSENSITIVE_QUALIFIED_PATH,
    CASE_INSENSITIVE_NAME,
    NONE
}
